### ISSUE TITLE
Constantly crashing API on SheetWorkerChatOutput

### ISSUE THREAD

**Issue by liquidox** [symposion/roll20-shaped-scripts#464]
Tonight we ran a campaign for the first time in some weeks. The API was constantly crashing (about once every few mins) with these errors:

```
For reference, the error message generated was: TypeError: Cannot read property 'get' of null
TypeError: Cannot read property 'get' of null
    at SheetWorkerChatOutput.displaySheetChatOutput (apiscript.js:17497:27)
    at roll20.setAttrWithWorker (apiscript.js:13991:35)
    at /home/node/d20-api-server/api.js:2140:5
    at Function._.each._.forEach (/home/node/d20-api-server/node_modules/underscore/underscore.js:153:9)
    at handleSheetWorkerComplete (/home/node/d20-api-server/api.js:2139:5)
    at Timeout._onTimeout (/home/node/d20-api-server/api.js:2162:7)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

It's difficult to say what triggered it, as we had a group of players interacting with the sheets and using the token macros created by Companion.

**Comment by symposion** [comment]
Yeah, this is the turn change handler - see #453

**Comment by liquidox** [comment]
Ah ok, sorry for the dupe!

**Comment by symposion** [comment]
No worries, the other one got shut by mistake so you wouldn't have found it. Just making release 9.0.0 now

**Comment by liquidox** [comment]
Sweet!
